name: Terraform Deploy EKS with Karpenter

on:
  pull_request:
    types: [closed]
    paths:
      - '**.tf'
      - '**.tfvars'
      - 'modules/**'
      - '.github/workflows/deploy.yaml'

env:
  TF_VERSION: 1.5.0
  AWS_REGION: us-east-1 
  STATE_BUCKET: pengchao2022-terraform-state
  STATE_KEY: eks-karpenter/terraform.tfstate

# declare OIDC write privilige so that can connect to aws 
permissions:
  id-token: write
  contents: read

jobs:
  terraform-deploy:
    name: Terraform EKS karpenter ArgoCD Deployment
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false # close wrapper

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-EKS-Karpenter-Deploy

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ env.STATE_BUCKET }}" \
            -backend-config="key=${{ env.STATE_KEY }}" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="encrypt=true" \
            -reconfigure \
            -upgrade # force refresh cache

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false

      - name: Deploy & Configure Karpenter
        run: |
          # get the eks cluster info dynamicly
          CLUSTER_NAME=$(terraform output -raw cluster_name)
          CLUSTER_ENDPOINT=$(terraform output -raw cluster_endpoint)
          KARPENTER_ROLE_ARN=$(terraform output -raw karpenter_role_arn)
          
          echo "Connecting to Cluster: $CLUSTER_NAME"
          echo "Using Karpenter Role: $KARPENTER_ROLE_ARN"
          
          # update kubeconfig
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name $CLUSTER_NAME
          
          # helm install using the OCI repo 
          helm upgrade --install karpenter oci://public.ecr.aws/karpenter/karpenter \
            --namespace karpenter --create-namespace \
            --version "1.0.6" \
            --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=${KARPENTER_ROLE_ARN} \
            --set settings.clusterName=${CLUSTER_NAME} \
            --set settings.clusterEndpoint=${CLUSTER_ENDPOINT} \
            --set controller.resources.requests.cpu=50m \
            --set controller.resources.requests.memory=128Mi \
            --set controller.resources.limits.cpu=200m \
            --set controller.resources.limits.memory=512Mi \
            --set replicas=1 \
            --set webhook.enabled=false \
            --set-json tolerations='[{"operator": "Exists"}]' 

          # show the kapenter pod status
          echo "Checking Karpenter Pods deployment status..."
          kubectl get pods -n karpenter
          
          # karpenter wait 5 minutes
          echo "Waiting for Karpenter Controller to be fully Running..."
          kubectl wait --namespace karpenter \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/name=karpenter \
            --timeout=300s || (kubectl describe pods -n karpenter && exit 1)

          # make sure karpenter CRDs is ready
          echo "Waiting for Karpenter v1 CRDs to establish..."
          kubectl wait --for condition=established --timeout=90s crd/nodepools.karpenter.sh crd/ec2nodeclasses.karpenter.k8s.aws

          # create karpenter file
          cat <<-EOF | kubectl apply -f -
          apiVersion: karpenter.k8s.aws/v1
          kind: EC2NodeClass
          metadata:
            name: default
          spec:
            amiFamily: Custom
            role: "KarpenterNodeRole-${CLUSTER_NAME}"
            amiSelectorTerms:
              - name: "ubuntu-eks-1.30-*" # using the aws official Ubuntu K8s 1.30 image
                owner: "099720109477"     # Canonical ubuntu
            subnetSelectorTerms:
              - tags:
                  karpenter.sh/discovery: ${CLUSTER_NAME}
            securityGroupSelectorTerms:
              - tags:
                  aws:eks:cluster-name: ${CLUSTER_NAME}
            tags:
              karpenter.sh/discovery: ${CLUSTER_NAME}
          EOF

          # create NodePool file
          cat <<-EOF | kubectl apply -f -
          apiVersion: karpenter.sh/v1
          kind: NodePool
          metadata:
            name: default
          spec:
            template:
              spec:
                nodeClassRef:
                  group: karpenter.k8s.aws
                  kind: EC2NodeClass
                  name: default
                requirements:
                  - key: kubernetes.io/arch
                    operator: In
                    values: ["amd64"]
                  - key: kubernetes.io/os
                    operator: In
                    values: ["linux"]
                  - key: karpenter.k8s.aws/instance-family
                    operator: In
                    values: ["t3"]
                  - key: karpenter.k8s.aws/instance-size
                    operator: In
                    values: ["small"]
                  - key: karpenter.sh/capacity-type
                    operator: In
                    values: ["on-demand"]
            limits:
              cpu: "6"
              memory: 4Gi
            disruption:
              consolidationPolicy: WhenEmptyOrUnderutilized 
              consolidateAfter: 1m
          EOF

          # create deployment file
          cat <<-EOF | kubectl apply -f -
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: keep-nodes
            namespace: default
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: keep-nodes
            template:
              metadata:
                labels:
                  app: keep-nodes
              spec:
                containers:
                - name: pause
                  image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
                  resources:
                    requests:
                      cpu: "1"
                      memory: 1Gi
          EOF

     
      - name: Deploy Metrics Server
        run: |
          echo "Installing Metrics Server via Helm..."
          helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/
          helm repo update
          
          helm upgrade --install metrics-server metrics-server/metrics-server \
            --namespace kube-system \
            --set args='{--kubelet-insecure-tls}' \
            --atomic \
            --timeout 5m

      - name: Deploy ArgoCD
        run: |
          echo "Creating argocd namespace dynamically if not exists..."
          kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
          
          echo "Adding Argo Helm repository..."
          helm repo add argoproj https://argoproj.github.io/argo-helm
          helm repo update
          
          echo "Installing ArgoCD with LoadBalancer..."
          helm upgrade --install argocd argoproj/argo-cd \
            --namespace argocd \
            --version "7.1.1" \
            --set server.service.type=LoadBalancer \
            --set global.image.repository=quay.io/argoproj/argocd \
            --atomic \
            --timeout 5m

          echo "Waiting for ArgoCD Server Pod to be ready..."
          kubectl wait --namespace argocd \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/name=argocd-server \
            --timeout=180s

          echo "======================================================================"
          echo " ✅ArgoCD deployed successfully!"
          echo "======================================================================"
          echo "Run the following command to fetch the public domain(URL):"
          echo "kubectl get svc argocd-server -n argocd -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'; echo"
          echo "ArgoCD default username is: admin"
          echo "Run the following command to fetch the ArgoCD password:"
          echo "kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo"
          echo "======================================================================"